version: '3.1'

services:
  adagios_dev:
    image: opinkerfi/adagios-git:latest
    ports:
      - 8080:80
    volumes:
      - ./adagios:/opt/adagios
      - ./pynag:/opt/pynag
      - ./logs:/var/log/nagios

volumes:
  adagios:
  pynag:
  logs:
