version: '3.1'

services:
  adagios_dev:
    image: opinkerfi/adagios-git:latest
    ports:
      - 8080:80
    volumes:
      - ./adagios:/opt
      - ./pynag:/opt
      - ./logs:/var/log
      - ./log/httpd:/etc/httpd/logs

volumes:
  adagios:
  pynag:
  logs:
  httpd: